name: Django CI  # GitHub Actions에서 표시될 워크플로우 이름

# 워크플로우가 실행될 조건
on:
  push:
    branches: [ finished ]  # main 브랜치에 push할 때
  pull_request:
    branches: [ main ]  # main 브랜치로 PR 생성할 때

# 실행될 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 최신 버전에서 실행

    steps:
    # 1. 코드 가져오기
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    # .env 파일 생성 (시크릿 값들을 사용)
    - name: Create .env file
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

    # 3. Docker 설정
    - name: Docker Compose 실행
      run: docker compose up -d --build

    # 4. Django 테스트
    - name: Django 테스트 실행
      run: docker compose exec -T web python manage.py test

    # 5. 정리
    - name: Docker 정리
      run: docker compose down
      
  cd:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/finished'  # main 브랜치에 push될 때만 배포
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4

    # EC2 접속을 위한 SSH 키 설정
    - name: SSH 키 설정
      env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/aws.pem
        chmod 600 ~/.ssh/aws.pem
        
    # EC2에 배포
    - name: EC2에 배포
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no $USER@$HOST '
          cd ~/app/library_by_django_example &&
          git pull origin finished &&
          echo "DB_NAME=${{ secrets.DB_NAME }}" > .env &&
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env &&
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env &&
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env &&
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env &&
          docker compose down &&
          docker compose up -d --build
        '